on:
  # push:
  #   branches:
  #     - "*"
  schedule:
    # 6AM (7PM UTC)
    - cron: '* * * * *'
  workflow_dispatch: {}

name: Scrape Data

jobs:
  run:
    name: "Run script"
    runs-on: ubuntu-20.04
    container:
      image: "buildkite/puppeteer"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check SYDNEY
        run: npm start
        env:
          LOCATION_NAME: Sydney
          LOCATION_INPUT_ID: rbLocation168

      # - name: Check Greensborough
      #   run: npm start
      #   env:
      #     LOCATION_NAME: Greensborough
      #     LOCATION_INPUT_ID: rbLocation84
      #     # Greensborough Medical Centre
      #     # 9-13 Flintoff Street
      #     # Greensborough
