on:
  push:
    branches:
      - "*"
  schedule:
    # 6AM (7PM UTC)
    - cron: '2  19 * * *'

name: Scrape Data

jobs:
  run:
    name: "Run script"
    runs-on: ubuntu-20.04
    container:
      image: "buildkite/puppeteer"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check Melbourne CBD
        run: npm start
        env:
          LOCATION_NAME: Melbourne CBD
          LOCATION_INPUT_ID: rbLocation135
          # Bupa
          # Level 2, 717 Bourke Street
          # Docklands

      - name: Check Greensborough
        run: npm start
        env:
          LOCATION_NAME: Greensborough
          LOCATION_INPUT_ID: rbLocation84
          # Greensborough Medical Centre
          # 9-13 Flintoff Street
          # Greensborough
